name: DBDOCS_BUILD

on:
  push:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # DBDocs Install
      - name: Install dbdocs
        run: sudo npm install -g dbdocs

      #DBDocs Install Check
      - name: Check dbdocs
        run: dbdocs

      # Runs a set of commands using the runners shell
      - name: Update dbdocs project

        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
        run: dbdocs build ./ERD/Hook.dbml --project=Hook_killer
